-- MySQL Script generated by MySQL Workbench
-- Fri Sep 10 14:15:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema airport_database_example
-- -----------------------------------------------------
-- Копия базы данных с сайта: https://sql-academy.org/

-- -----------------------------------------------------
-- Schema airport_database_example
--
-- Копия базы данных с сайта: https://sql-academy.org/
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airport_database_example` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `airport_database_example` ;

-- -----------------------------------------------------
-- Table `airport_database_example`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport_database_example`.`Company` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport_database_example`.`Passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport_database_example`.`Passenger` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL COMMENT 'Имя пассажира',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport_database_example`.`Pass_in_trip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport_database_example`.`Pass_in_trip` (
  `id` INT NOT NULL,
  `trip` INT NULL COMMENT 'Идентификатор билета',
  `passenger` INT NOT NULL COMMENT 'Идентификатор пассажира',
  `place` VARCHAR(45) NULL COMMENT 'Посадочное место в самолете',
  PRIMARY KEY (`id`, `passenger`),
  INDEX `id_idx` (`passenger` ASC) INVISIBLE,
  INDEX `idx_fk_trip` (`trip` ASC) VISIBLE,
    FOREIGN KEY (`passenger`)
    REFERENCES `airport_database_example`.`Passenger` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport_database_example`.`Trip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport_database_example`.`Trip` (
  `id` INT NOT NULL,
  `company` INT NOT NULL COMMENT 'Идентификатор компании-перевозчика',
  `plane` VARCHAR(45) NULL COMMENT 'Модель самолёта',
  `town_from` VARCHAR(45) NULL COMMENT 'Город вылета',
  `town_to` VARCHAR(45) NULL COMMENT 'Город прилёта',
  `time_out` DATETIME NULL COMMENT 'Время вылета',
  `time_in` DATETIME NULL COMMENT 'Время прилета',
  INDEX `id_idx` (`company` ASC) VISIBLE,
  PRIMARY KEY (`id`, `company`),
    FOREIGN KEY (`company`)
    REFERENCES `airport_database_example`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`id`)
    REFERENCES `airport_database_example`.`Pass_in_trip` (`trip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
